//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartLanches
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedidos
    {
        public int nr_pedido { get; set; }
        public Nullable<int> cd_status_pedido { get; set; }
        public Nullable<System.DateTime> dt_entrada_pedido { get; set; }
        public Nullable<System.DateTime> dt_inicio_preparacao { get; set; }
        public Nullable<System.DateTime> dt_termino_preparacao { get; set; }
        public Nullable<int> cd_lanche { get; set; }
        public Nullable<int> cd_alface { get; set; }
        public Nullable<int> cd_bacon { get; set; }
        public Nullable<int> cd_hamburguer_carne { get; set; }
        public Nullable<int> cd_ovo { get; set; }
        public Nullable<int> cd_queijo { get; set; }
        public Nullable<double> vl_pedido { get; set; }
    }
}
