//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RafaDBEntities : DbContext
    {
        public RafaDBEntities()
            : base("name=RafaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_ingrendientes> tb_ingrendientes { get; set; }
        public virtual DbSet<tb_lanches> tb_lanches { get; set; }
        public virtual DbSet<tb_promocoes> tb_promocoes { get; set; }
        public virtual DbSet<tb_pedidos> tb_pedidos { get; set; }
    
        public virtual int sp_calcula_lanche(Nullable<int> cd_alface, Nullable<int> cd_bacon, Nullable<int> cd_hamburguer_carne, Nullable<int> cd_ovo, Nullable<int> cd_queijo, ObjectParameter vl_soma_valor)
        {
            var cd_alfaceParameter = cd_alface.HasValue ?
                new ObjectParameter("cd_alface", cd_alface) :
                new ObjectParameter("cd_alface", typeof(int));
    
            var cd_baconParameter = cd_bacon.HasValue ?
                new ObjectParameter("cd_bacon", cd_bacon) :
                new ObjectParameter("cd_bacon", typeof(int));
    
            var cd_hamburguer_carneParameter = cd_hamburguer_carne.HasValue ?
                new ObjectParameter("cd_hamburguer_carne", cd_hamburguer_carne) :
                new ObjectParameter("cd_hamburguer_carne", typeof(int));
    
            var cd_ovoParameter = cd_ovo.HasValue ?
                new ObjectParameter("cd_ovo", cd_ovo) :
                new ObjectParameter("cd_ovo", typeof(int));
    
            var cd_queijoParameter = cd_queijo.HasValue ?
                new ObjectParameter("cd_queijo", cd_queijo) :
                new ObjectParameter("cd_queijo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_calcula_lanche", cd_alfaceParameter, cd_baconParameter, cd_hamburguer_carneParameter, cd_ovoParameter, cd_queijoParameter, vl_soma_valor);
        }
    
        public virtual int sp_faz_pedido(string nm_cliente, string nm_lanche, Nullable<int> cd_lanche, Nullable<int> cd_alface, Nullable<int> cd_bacon, Nullable<int> cd_hamburguer_carne, Nullable<int> cd_ovo, Nullable<int> cd_queijo)
        {
            var nm_clienteParameter = nm_cliente != null ?
                new ObjectParameter("nm_cliente", nm_cliente) :
                new ObjectParameter("nm_cliente", typeof(string));
    
            var nm_lancheParameter = nm_lanche != null ?
                new ObjectParameter("nm_lanche", nm_lanche) :
                new ObjectParameter("nm_lanche", typeof(string));
    
            var cd_lancheParameter = cd_lanche.HasValue ?
                new ObjectParameter("cd_lanche", cd_lanche) :
                new ObjectParameter("cd_lanche", typeof(int));
    
            var cd_alfaceParameter = cd_alface.HasValue ?
                new ObjectParameter("cd_alface", cd_alface) :
                new ObjectParameter("cd_alface", typeof(int));
    
            var cd_baconParameter = cd_bacon.HasValue ?
                new ObjectParameter("cd_bacon", cd_bacon) :
                new ObjectParameter("cd_bacon", typeof(int));
    
            var cd_hamburguer_carneParameter = cd_hamburguer_carne.HasValue ?
                new ObjectParameter("cd_hamburguer_carne", cd_hamburguer_carne) :
                new ObjectParameter("cd_hamburguer_carne", typeof(int));
    
            var cd_ovoParameter = cd_ovo.HasValue ?
                new ObjectParameter("cd_ovo", cd_ovo) :
                new ObjectParameter("cd_ovo", typeof(int));
    
            var cd_queijoParameter = cd_queijo.HasValue ?
                new ObjectParameter("cd_queijo", cd_queijo) :
                new ObjectParameter("cd_queijo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_faz_pedido", nm_clienteParameter, nm_lancheParameter, cd_lancheParameter, cd_alfaceParameter, cd_baconParameter, cd_hamburguer_carneParameter, cd_ovoParameter, cd_queijoParameter);
        }
    }
}
