//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ingrendientes
    {
        public int cd_ingrediente { get; set; }
        public string nm_ingrediente { get; set; }
        public Nullable<int> cd_x_bacon_possui { get; set; }
        public Nullable<int> cd_x_burger_possui { get; set; }
        public Nullable<int> cd_x_egg_possui { get; set; }
        public Nullable<int> cd_x_egg_bacon_possui { get; set; }
        public Nullable<double> vl_valor { get; set; }
    }
}
